### ISSUE TITLE
Ars Lectern not working with EMI

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#401]
### Modpack Version

1.19.0

### Describe your issue.

Since JEI was removed, the Ars Lectern's synced search doesn't work with EMI. Additionally, you can't use EMI to populate items when crafting if you have them in storage.

![Image](https://github.com/user-attachments/assets/a9e1e703-cc83-49b9-9dbf-82dd0949fb4a)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment]
The latter should be fixed in 1.20(plus button not working),  but ars has not added EMI sync yet, native EMI compat is a work in progress there still

**Comment by SupaJordy** [comment]
Thanks @theboo - I look forward to 1.20

**Comment by SupaJordy** [comment]
Downloaded 1.20 and did a quick test. Initially I tried doing oak planks and the button came up to add items but when I clicked it the crafting table remained empty. I thought it wasn't working but when I try something like a diamond block or polished andesite it works fine.

I set the recipe tree to favour oak logs for oak planks but still doesn't add the items. Tested with spruce logs/planks too and got the same results.

I'll try some more complicated recipes tomorrow.

**Comment by SupaJordy** [comment]
Having checked again, all recipes seem to work apart from some that require only one item, ie. planks and buttons. Gold powder seems to work ok. Not a big deal, just thought I'd mention it.

**Comment by theboo** [comment]
Gonna ping @Vonr here, they may have some insight as they're the one doing the EMI compat in ars. I'm on vacation so can't do any testing myself.
